name: build and run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CC: gcc-11
      CXX: g++-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # # install dependencies
      #- name: boost
      #  run: sudo apt-get update && sudo apt-get install -yq libboost1.65-dev
      # build project
      - name: mkdir
        run: mkdir build
      - name: cmake build
        run: cmake -Bbuild -H.
      - name: cmake make
        run: cmake --build build/ --target all
      # run tests
      - name: Unit tests
        run: build/lsqecc_tests --gtest_filter=*
      - name: Regression tests
        run: ./suite.py